CREATE TABLE "TB_MBR_MST" (
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"ID"	VARCHAR2(32)		NOT NULL,
	"NICKNAME"	VARCHAR2(10)		NOT NULL,
	"EMAIL"	VARCHAR2(64)		NOT NULL,
	"PASSWD"	VARCHAR2(64)		NOT NULL,
	"FLG_PETS"	CHAR(1)		NOT NULL,
	"PETS"	CAHR(5)		NULL,
	"CD_STATE"	NUMBER(3)		NOT NULL,
	"MBR_NM"	VARCHAR2(64)		NOT NULL,
	"GENDER"	CHAR(1)		NOT NULL,
	"PHONE"	VARCHAR2(64)		NOT NULL,
	"LAST_IP"	VARCHAR2(16)		NULL,
	"LAST_DT"	DATE		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_MBR_MST"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_MBR_MST"."ID" IS '아이디';

COMMENT ON COLUMN "TB_MBR_MST"."NICKNAME" IS '닉네임';

COMMENT ON COLUMN "TB_MBR_MST"."EMAIL" IS '이메일';

COMMENT ON COLUMN "TB_MBR_MST"."PASSWD" IS '비밀번호';

COMMENT ON COLUMN "TB_MBR_MST"."FLG_PETS" IS '반려동물 여부';

COMMENT ON COLUMN "TB_MBR_MST"."PETS" IS '반려동물 (예: YYYYY)';

COMMENT ON COLUMN "TB_MBR_MST"."CD_STATE" IS '상태코드: 대기(0), 정상(1), 탈퇴(8), 강퇴(9)';

COMMENT ON COLUMN "TB_MBR_MST"."MBR_NM" IS '성명';

COMMENT ON COLUMN "TB_MBR_MST"."GENDER" IS '성별: 남자(M), 여자(F)';

COMMENT ON COLUMN "TB_MBR_MST"."PHONE" IS '연락처';

COMMENT ON COLUMN "TB_MBR_MST"."LAST_IP" IS '마지막 로그인IP';

COMMENT ON COLUMN "TB_MBR_MST"."LAST_DT" IS '마지막 로그인 일시';

COMMENT ON COLUMN "TB_MBR_MST"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_MBR_MST"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_MBR_MST"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_MBR_MST"."UPDATER" IS '수정자';

CREATE TABLE "TB_BUY_MST" (
	"SEQ_BUY_MST"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"BUY_INFO"	VARCHAR2(128)		NOT NULL,
	"BUY_COUNT"	NUMBER(3)		NOT NULL,
	"BUY_PRICE"	NUMBER(10)		NOT NULL,
	"FLG_DELETE"	CHAR(1)		NULL,
	"CD_STATE_PAY"	CHAR(1)		NULL,
	"CD_STATE_DELIVERY"	CHAR(1)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_BUY_MST"."SEQ_BUY_MST" IS '구매 마스터 일련번호';

COMMENT ON COLUMN "TB_BUY_MST"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_BUY_MST"."BUY_INFO" IS '구매상품정보(예: 퓨리나 인도어 캣사료)';

COMMENT ON COLUMN "TB_BUY_MST"."BUY_COUNT" IS '구매 상품 총 갯수';

COMMENT ON COLUMN "TB_BUY_MST"."BUY_PRICE" IS '구매 상품 총 금액';

COMMENT ON COLUMN "TB_BUY_MST"."FLG_DELETE" IS '삭제여부';

COMMENT ON COLUMN "TB_BUY_MST"."CD_STATE_PAY" IS '결제상태코드: 결제전(NULL),성공(Y),실패(N),취소(C)';

COMMENT ON COLUMN "TB_BUY_MST"."CD_STATE_DELIVERY" IS '배송상태코드: 등록시(NULL),확인중(C),배송준비중(P),배송중(D),배송 완료(Y)';

COMMENT ON COLUMN "TB_BUY_MST"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_BUY_MST"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_BUY_MST"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_BUY_MST"."UPDATER" IS '수정자';

CREATE TABLE "TB_MNG" (
	"SEQ_MNG"	NUMBER(10)		NOT NULL,
	"ID"	VARCHAR2(32)		NOT NULL,
	"PASSWD"	VARCHAR2(32)		NOT NULL,
	"CD_STATE"	NUMBER(3)		NOT NULL,
	"MNG_NM"	VARCHAR2(32)		NOT NULL,
	"EMAIL"	VARCHAR2(32)		NOT NULL,
	"PHONE"	VARCHAR2(16)		NOT NULL,
	"POST"	VARCHAR2(8)		NULL,
	"ADDR1"	VARCHAR2(128)		NULL,
	"ADDR2"	VARCHAR2(128)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL,
	"NICKNAME"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "TB_MNG"."SEQ_MNG" IS '관리자';

COMMENT ON COLUMN "TB_MNG"."ID" IS '아이디';

COMMENT ON COLUMN "TB_MNG"."PASSWD" IS '비밀번호';

COMMENT ON COLUMN "TB_MNG"."CD_STATE" IS '상태코드: 대기(0), 정상(1), 반려(2), 탈퇴(8), 강퇴(9)';

COMMENT ON COLUMN "TB_MNG"."MNG_NM" IS '성명';

COMMENT ON COLUMN "TB_MNG"."EMAIL" IS '이메일';

COMMENT ON COLUMN "TB_MNG"."PHONE" IS '연락처';

COMMENT ON COLUMN "TB_MNG"."POST" IS '우편번호';

COMMENT ON COLUMN "TB_MNG"."ADDR1" IS '주소1';

COMMENT ON COLUMN "TB_MNG"."ADDR2" IS '주소2';

COMMENT ON COLUMN "TB_MNG"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_MNG"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_MNG"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_MNG"."UPDATER" IS '수정자';

COMMENT ON COLUMN "TB_MNG"."NICKNAME" IS '닉네임';

CREATE TABLE "TB_PRD" (
	"SEQ_PRD"	NUMBER(10)		NOT NULL,
	"PRD_NM"	VARCHAR2(128)		NOT NULL,
	"CD_CTG"	CHAR(2)		NOT NULL,
	"PRICE_COST"	NUMBER(10)		NOT NULL,
	"COUNT_STOCK"	NUMBER(10)		NOT NULL,
	"FLG_DELETE"	CHAR(1)		NOT NULL,
	"CD_STATE_PRD"	CHAR(1)		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_PRD"."SEQ_PRD" IS '상품일련번호';

COMMENT ON COLUMN "TB_PRD"."PRD_NM" IS '상품명';

COMMENT ON COLUMN "TB_PRD"."CD_CTG" IS '상품 카테고리:1x(강아지),2x(고양이),3x(햄스터),4x(파충류)';

COMMENT ON COLUMN "TB_PRD"."PRICE_COST" IS '상품 원가';

COMMENT ON COLUMN "TB_PRD"."COUNT_STOCK" IS '상품 재고';

COMMENT ON COLUMN "TB_PRD"."FLG_DELETE" IS '삭제 여부';

COMMENT ON COLUMN "TB_PRD"."CD_STATE_PRD" IS '판매상품상태 코드:대기(0),승인(1),중지(2),반려(3),품절(9)';

COMMENT ON COLUMN "TB_PRD"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_PRD"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_PRD"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_PRD"."UPDATER" IS '수정자';

CREATE TABLE "TB_SLE" (
	"SEQ_SLE"	NUMBER(10)		NOT NULL,
	"SEQ_PRD"	NUMBER(10)		NOT NULL,
	"SLE_NM"	VARCHAR2(256)		NOT NULL,
	"DESCES"	VARCHAR2(2048)		NOT NULL,
	"IMG"	VARCHAR2(256)		NULL,
	"PRICE_SALE"	NUMBER(10)		NOT NULL,
	"CD_STATE_SALE"	CHAR(3)		NOT NULL,
	"DT_SALE_START"	DATE		NOT NULL,
	"DT_SALE_END"	DATE		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_SLE"."SEQ_SLE" IS '판매 상품 일련번호';

COMMENT ON COLUMN "TB_SLE"."SEQ_PRD" IS '상품일련번호';

COMMENT ON COLUMN "TB_SLE"."SLE_NM" IS '판매 상품명';

COMMENT ON COLUMN "TB_SLE"."DESCES" IS '판매 상품 설명';

COMMENT ON COLUMN "TB_SLE"."IMG" IS '이미지(대표)';

COMMENT ON COLUMN "TB_SLE"."PRICE_SALE" IS '판매가격';

COMMENT ON COLUMN "TB_SLE"."CD_STATE_SALE" IS '판매상품상태코드: 대기(0), 승인(1),중지(2),반려(3).품절(9)';

COMMENT ON COLUMN "TB_SLE"."DT_SALE_START" IS '판매 시작 일시';

COMMENT ON COLUMN "TB_SLE"."DT_SALE_END" IS '판매 종료 일시';

COMMENT ON COLUMN "TB_SLE"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_SLE"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_SLE"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_SLE"."UPDATER" IS '수정자';

CREATE TABLE "TB_BUY_DTL" (
	"SEQ_BUY_DTL"	NUMBER(19)		NOT NULL,
	"SEQ_BUY_MST"	NUMBER(19)		NOT NULL,
	"SEQ_SLE"	NUMBER(10)		NOT NULL,
	"SEQ_PRD"	NUMBER(10)		NOT NULL,
	"COUNT"	NUMBER(3)		NOT NULL,
	"PRICE"	NUMBER(10)		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"SEQ_SLE2"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_BUY_DTL"."SEQ_BUY_DTL" IS '구매 상세 일련번호';

COMMENT ON COLUMN "TB_BUY_DTL"."SEQ_BUY_MST" IS '구매 마스터 일련번호';

COMMENT ON COLUMN "TB_BUY_DTL"."SEQ_SLE" IS '판매상품 일련번호';

COMMENT ON COLUMN "TB_BUY_DTL"."SEQ_PRD" IS '상품 일련번호';

COMMENT ON COLUMN "TB_BUY_DTL"."COUNT" IS '판매 상품 개수';

COMMENT ON COLUMN "TB_BUY_DTL"."PRICE" IS '판매 상품 가격';

COMMENT ON COLUMN "TB_BUY_DTL"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_BUY_DTL"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_BUY_DTL"."SEQ_SLE2" IS '판매 상품 일련번호';

CREATE TABLE "TB_PAY" (
	"SEQ_PAY"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"SEQ_BUY_MST"	NUMBER(19)		NOT NULL,
	"CD_PG"	NUMBER(3)		NOT NULL,
	"DEAL_NUM"	VARCHAR2(64)		NOT NULL,
	"CD_RESPONSE"	VARCHAR2(8)		NULL,
	"CD_PAY_METHOD"	NUMBER(3)		NOT NULL,
	"FLG_SUCCESS"	CHAR(1)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(3)		NOT NULL
);

COMMENT ON COLUMN "TB_PAY"."SEQ_PAY" IS '결제 일련번호';

COMMENT ON COLUMN "TB_PAY"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_PAY"."SEQ_BUY_MST" IS '구매 마스터 일련번호';

COMMENT ON COLUMN "TB_PAY"."CD_PG" IS 'PG사 코드: 페이업(1)';

COMMENT ON COLUMN "TB_PAY"."DEAL_NUM" IS '거래(트랜잭션)번호';

COMMENT ON COLUMN "TB_PAY"."CD_RESPONSE" IS '응답코드';

COMMENT ON COLUMN "TB_PAY"."CD_PAY_METHOD" IS '결제수단 코드(예: 카드, 이체 등)';

COMMENT ON COLUMN "TB_PAY"."FLG_SUCCESS" IS '성공여부: 기본 (NULL), 성공(Y), 실패(N)';

COMMENT ON COLUMN "TB_PAY"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_PAY"."REGISTER" IS '등록자';

CREATE TABLE "TB_BBS" (
	"SEQ_BBS"	NUMBER(10)		NOT NULL,
	"SEQ_BBS_PARENT"	NUMBER(10)		NULL,
	"CD_BBS_TYPE"	NUMBER(3)		NULL,
	"TITLE"	VARCHAR2(256)		NOT NULL,
	"CD_CTG"	NUMBER(3)		NOT NULL,
	"CD_CTG_PET"	NUMBER(3)		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"FLG_TOP"	CHAR(1)		NULL,
	"FLG_REPLY"	CHAR(1)		NULL,
	"FLG_DELETE"	CHAR(1)		NULL,
	"READED"	NUMBER(10)		NULL,
	"FILE_SAVE"	VARCHAR2(256)		NULL,
	"FILE_ORIG"	VARCHAR2(64)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_BBS"."SEQ_BBS" IS '게시판 일련번호';

COMMENT ON COLUMN "TB_BBS"."SEQ_BBS_PARENT" IS '게시판 상위 일련번호';

COMMENT ON COLUMN "TB_BBS"."CD_BBS_TYPE" IS '게시판 타입 코드: 공지사항(1) FAQ(2) 문의(3) 자유게시판(4) QnA(5) 입양후기(6) 자랑글(7)';

COMMENT ON COLUMN "TB_BBS"."TITLE" IS '제목';

COMMENT ON COLUMN "TB_BBS"."CD_CTG" IS '카테고리: 가입및탈퇴(1), 입양(2),구매(3),결제(4),배송(5),환불(6),후원(7),커뮤니티(8),기타(9)';

COMMENT ON COLUMN "TB_BBS"."CD_CTG_PET" IS '카테고리:강아지(1),고양이(2),햄스터(3),파충류(4),기타(5)';

COMMENT ON COLUMN "TB_BBS"."CONTENT" IS '내용';

COMMENT ON COLUMN "TB_BBS"."FLG_TOP" IS '최상위여부 (공지사항,인기글 등)';

COMMENT ON COLUMN "TB_BBS"."FLG_REPLY" IS '답변여부';

COMMENT ON COLUMN "TB_BBS"."FLG_DELETE" IS '삭제여부';

COMMENT ON COLUMN "TB_BBS"."READED" IS '조회수';

COMMENT ON COLUMN "TB_BBS"."FILE_SAVE" IS '파일 저장명 (경로포함)';

COMMENT ON COLUMN "TB_BBS"."FILE_ORIG" IS '파일 원본명';

COMMENT ON COLUMN "TB_BBS"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_BBS"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_BBS"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_BBS"."UPDATER" IS '수정자';

CREATE TABLE "TB_MBR_DTL" (
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"POST"	VARCHAR2(32)		NOT NULL,
	"ADDR1"	VARCHAR2(256)		NOT NULL,
	"ADDR2"	VARCHAR2(256)		NOT NULL,
	"FLG_SMS"	CHAR(1)		NOT NULL,
	"DT_SMS"	DATE		NOT NULL,
	"FLG_EMAIL"	CHAR(1)		NOT NULL,
	"DT_EMAIL"	DATE		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_MBR_DTL"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_MBR_DTL"."POST" IS '우편번호';

COMMENT ON COLUMN "TB_MBR_DTL"."ADDR1" IS '주소1';

COMMENT ON COLUMN "TB_MBR_DTL"."ADDR2" IS '주소2';

COMMENT ON COLUMN "TB_MBR_DTL"."FLG_SMS" IS '수신여부 SMS';

COMMENT ON COLUMN "TB_MBR_DTL"."DT_SMS" IS '수신여부 SMS 일시';

COMMENT ON COLUMN "TB_MBR_DTL"."FLG_EMAIL" IS '수신여부 EMAIL';

COMMENT ON COLUMN "TB_MBR_DTL"."DT_EMAIL" IS '수신여부 EMAIL 일시';

COMMENT ON COLUMN "TB_MBR_DTL"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_MBR_DTL"."UPDATER" IS '수정자';

CREATE TABLE "TB_TRM_AGR" (
	"SEQ_TRM_AGR"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"SEQ_TRM"	NUMBER(3)		NOT NULL,
	"FLG_AGR"	CHAR(1)		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_TRM_AGR"."SEQ_TRM_AGR" IS '약관동의 일련번호';

COMMENT ON COLUMN "TB_TRM_AGR"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_TRM_AGR"."SEQ_TRM" IS '약관 일련번호';

COMMENT ON COLUMN "TB_TRM_AGR"."FLG_AGR" IS '수락여부';

COMMENT ON COLUMN "TB_TRM_AGR"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_TRM_AGR"."REGISTER" IS '등록자';

CREATE TABLE "TB_STAT_MBR" (
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"POST"	VARCHAR2(5)		NOT NULL
);

COMMENT ON COLUMN "TB_STAT_MBR"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_STAT_MBR"."POST" IS '우편번호';

CREATE TABLE "TB_BSK" (
	"SEQ_BSK"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"SEQ_SLE"	NUMBER(10)		NOT NULL,
	"SEQ_PRD"	NUMBER(10)		NOT NULL,
	"SLE_NM"	VARCHAR2(256)		NOT NULL,
	"PRICE"	NUMBER(10)		NOT NULL,
	"COUNT"	NUMBER(3)		NOT NULL,
	"IMG"	VARCHAR2(256)		NOT NULL,
	"FLG_DELETE"	CHAR(1)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"DT_UPT"	DATE		NULL
);

COMMENT ON COLUMN "TB_BSK"."SEQ_BSK" IS '장바구니 일련번호';

COMMENT ON COLUMN "TB_BSK"."SEQ_MBR" IS '회원 일련번호';

COMMENT ON COLUMN "TB_BSK"."SEQ_SLE" IS '판매 상품일련번호';

COMMENT ON COLUMN "TB_BSK"."SEQ_PRD" IS '상품 일련번호';

COMMENT ON COLUMN "TB_BSK"."SLE_NM" IS '판매 상품명';

COMMENT ON COLUMN "TB_BSK"."PRICE" IS '판매 상품 가격';

COMMENT ON COLUMN "TB_BSK"."COUNT" IS '구매수량';

COMMENT ON COLUMN "TB_BSK"."IMG" IS '판매상품이미지';

COMMENT ON COLUMN "TB_BSK"."FLG_DELETE" IS '삭제여부';

COMMENT ON COLUMN "TB_BSK"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_BSK"."DT_UPT" IS '수정일시';

CREATE TABLE "TB_SLE_IMG" (
	"SEQ_SLE_IMG"	NUMBER(10)		NOT NULL,
	"SEQ_SLE"	NUMBER(10)		NOT NULL,
	"IMG"	VARCHAR2(256)		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_SLE_IMG"."SEQ_SLE_IMG" IS '판매 상품 이미지 일련번호';

COMMENT ON COLUMN "TB_SLE_IMG"."SEQ_SLE" IS '판매 상품 일련번호';

COMMENT ON COLUMN "TB_SLE_IMG"."IMG" IS '이미지';

COMMENT ON COLUMN "TB_SLE_IMG"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_SLE_IMG"."REGISTER" IS '등록자';

CREATE TABLE "TB_LIKE" (
	"SEQ_LIKE"	NUMBER(10)		NOT NULL,
	"FLG_LIKE"	CHAR(1)		NOT NULL,
	"LIKE_COUNT"	NUMBER(38)		NOT NULL,
	"CD_CTG"	NUMBER(3)		NULL,
	"Field"	VARCHAR(255)		NULL,
	"Field2"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "TB_LIKE"."SEQ_LIKE" IS '좋아요 일련번호';

COMMENT ON COLUMN "TB_LIKE"."FLG_LIKE" IS '좋아요 여부';

COMMENT ON COLUMN "TB_LIKE"."LIKE_COUNT" IS '좋아요 개수';

COMMENT ON COLUMN "TB_LIKE"."CD_CTG" IS '카테고리 : 상품(0) , 입양(1),  게시글(2),  댓글(3)';

ALTER TABLE "TB_MBR_MST" ADD CONSTRAINT "PK_TB_MBR_MST" PRIMARY KEY (
	"SEQ_MBR"
);

ALTER TABLE "TB_BUY_MST" ADD CONSTRAINT "PK_TB_BUY_MST" PRIMARY KEY (
	"SEQ_BUY_MST"
);

ALTER TABLE "TB_MNG" ADD CONSTRAINT "PK_TB_MNG" PRIMARY KEY (
	"SEQ_MNG"
);

ALTER TABLE "TB_PRD" ADD CONSTRAINT "PK_TB_PRD" PRIMARY KEY (
	"SEQ_PRD"
);

ALTER TABLE "TB_SLE" ADD CONSTRAINT "PK_TB_SLE" PRIMARY KEY (
	"SEQ_SLE"
);

ALTER TABLE "TB_BUY_DTL" ADD CONSTRAINT "PK_TB_BUY_DTL" PRIMARY KEY (
	"SEQ_BUY_DTL"
);

ALTER TABLE "TB_PAY" ADD CONSTRAINT "PK_TB_PAY" PRIMARY KEY (
	"SEQ_PAY"
);

ALTER TABLE "TB_BBS" ADD CONSTRAINT "PK_TB_BBS" PRIMARY KEY (
	"SEQ_BBS"
);

ALTER TABLE "TB_MBR_DTL" ADD CONSTRAINT "PK_TB_MBR_DTL" PRIMARY KEY (
	"SEQ_MBR"
);

ALTER TABLE "TB_TRM_AGR" ADD CONSTRAINT "PK_TB_TRM_AGR" PRIMARY KEY (
	"SEQ_TRM_AGR"
);

ALTER TABLE "TB_STAT_MBR" ADD CONSTRAINT "PK_TB_STAT_MBR" PRIMARY KEY (
	"SEQ_MBR"
);

ALTER TABLE "TB_BSK" ADD CONSTRAINT "PK_TB_BSK" PRIMARY KEY (
	"SEQ_BSK"
);

ALTER TABLE "TB_SLE_IMG" ADD CONSTRAINT "PK_TB_SLE_IMG" PRIMARY KEY (
	"SEQ_SLE_IMG"
);

ALTER TABLE "TB_MBR_DTL" ADD CONSTRAINT "FK_TB_MBR_MST_TO_TB_MBR_DTL_1" FOREIGN KEY (
	"SEQ_MBR"
)
REFERENCES "TB_MBR_MST" (
	"SEQ_MBR"
);

ALTER TABLE "TB_STAT_MBR" ADD CONSTRAINT "FK_TB_MBR_MST_TO_TB_STAT_MBR_1" FOREIGN KEY (
	"SEQ_MBR"
)
REFERENCES "TB_MBR_MST" (
	"SEQ_MBR"
);

